driver-architecture: bus infrastructure is itself a framework
bootlin/training-materials pull request #243
Opened 2024-05-06 09:04 UTC by arnout

This is explained much later in the training, but I think it's important to mention this early on already. Otherwise, things that are explained immediately afterwards don't make much sense (e.g. the fact that you have a struct device twice: once for the bus and once for the functional framewoek).

While using the bootlin materials for an internal training, there are a few improvements I made (at least, I consider them improvments myself). Since you probably don't agree with all of them, I'm making separate PRs for each. Feel free to close the PR if you disagree with the idea.

2024-05-06 12:39 UTC, miquelraynal requested changes
It is totally true we don't explain well the fact that we have in the end several struct devices for the same physical device, but:
- it's not always the case (welcome in the kernel world)
- it feels way too early here before we can talk about this

However I would suggest to add your modified figure when we talk about the device model being recursive? We could maybe even have a bit of text explaining the double struct device thing there. This way the learning curve is not too steep at the very beginning.

2024-10-28 09:42 UTC, Tropicao commented
Hello @arnout, are you planning to update your PR with @miquelraynal 's suggestion ?

2024-10-30 13:39 UTC, arnout commented
It's been too long ago and I no longer have the context to understand what I was even trying to do here...

2025-06-06 09:08 UTC, Tropicao commented
Closing stalled PR, feel free to reopen if this becomes relevant again

2025-06-06 09:08 UTC, closed without merging