Update to Dunfell and enable DK2 support
bootlin/training-materials pull request #37
Opened 2021-06-23 06:43 UTC by tprrt

2021-07-02 15:31 UTC, alexandrebelloni requested changes

2021-07-02 15:31 UTC, alexandrebelloni commented on slides/yocto-advanced/yocto-advanced.tex
> +      highest version number, from layer with the highest priority, unless the recipe defines
"from the highest priority layer" also, please wrap that line properly

2021-07-02 15:32 UTC, alexandrebelloni requested changes

2021-07-02 15:32 UTC, alexandrebelloni commented on slides/yocto-advanced/yocto-advanced.tex
> +$ find -atime +30 -delete $SSTATE_DIR
This doesn't necessarily work on filesystem mounted with noatime which is very common on build machines so at least add a description of what this does

2021-07-02 15:33 UTC, alexandrebelloni approved these changes

2021-07-02 15:33 UTC, alexandrebelloni approved these changes

2021-07-02 15:33 UTC, alexandrebelloni approved these changes

2021-07-02 15:34 UTC, alexandrebelloni requested changes

2021-07-02 15:34 UTC, alexandrebelloni commented on slides/yocto-image/yocto-image.tex
> +    \item Be careful about the \code{PACKAGE_ARCH} value.
This needs more details

2021-07-02 15:38 UTC, alexandrebelloni commented on slides/yocto-recipe-extra/yocto-recipe-extra.tex
> +python __anonymous() { # or python () {
I'll settle for simply `python __anonymous()`

2021-07-02 15:39 UTC, alexandrebelloni approved these changes

2021-07-02 15:39 UTC, alexandrebelloni approved these changes

2021-07-02 15:40 UTC, alexandrebelloni commented on slides/yocto-sdk/yocto-sdk.tex
> +    \item To modify the source of an existing recipe: \code{devtool modify <recipe>}
devtool modify allows to both modify the recipe itself and the sources of the targeted application so I'm not sure about that change

2021-07-02 15:42 UTC, alexandrebelloni commented on labs/yocto-advanced-configuration-stm32/yocto-advanced-configuration-stm32.tex
> +for the \code{stm32mp157a-dk1-sdcard} configuration:
I would think `\code{stm32mp157a-dk1-sdcard}` also has to be changed

2021-07-02 15:42 UTC, alexandrebelloni approved these changes

2021-07-05 06:55 UTC, tprrt commented on slides/yocto-image/yocto-image.tex
> +    \item Be careful about the \code{PACKAGE_ARCH} value.
Added some details about PACKAGE_ARCH

2021-07-09 16:36 UTC, alexandrebelloni commented
Merged

2021-07-09 16:36 UTC, closed without merging